[files]
extend-exclude = ["nectar_dashboard/usage/static/js/DataTables/*", "nectar_dashboard/rcallocation/migrations/", "nectar_dashboard/rcallocation/forcodes.py", "nectar_dashboard/rcallocation/tests/unit/test_utils.py"]


[default.extend-words]
ACN = "ACN"
ANDS = "ANDS"
HASS = "HASS"

[default.extend-identifiers]
FoR = "FoR"
FoRChoiceField = "FoRChoiceField"
