[tool.ruff]
line-length = 79
# see https://github.com/astral-sh/ruff/issues/4560
ignore = ["E712", "F405"]

[tool.ruff.format]
quote-style = "preserve"
docstring-code-format = true

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "U"]
