# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-25 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rcallocation', '0029_python3isms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationrequest',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Date'),
        ),
    ]
