# Generated by Django 1.11.11 on 2019-07-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rcallocation', '0031_submit_date-to-time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationrequest',
            name='end_date',
            field=models.DateField(
                editable=False,
                help_text='The day when the allocation ends.',
                null=True,
                verbose_name='End date',
            ),
        ),
        migrations.AlterField(
            model_name='allocationrequest',
            name='start_date',
            field=models.DateField(
                editable=False,
                help_text='The day when the allocation starts',
                null=True,
                verbose_name='Start date',
            ),
        ),
    ]
