# Generated by Django 1.11.11 on 2019-07-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rcallocation', '0034_remove-sa'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
