# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-19 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcallocation', '0035_add-zone-enabled-field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approver',
            fields=[
                ('name', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='approver',
            name='sites',
            field=models.ManyToManyField(to='rcallocation.Site'),
        ),
    ]
