# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-08 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcallocation', '0035_add-zone-enabled-field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('display_name', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='zone',
            name='kind',
            field=models.CharField(choices=[('S', 'Storage'), ('C', 'Compute')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='approver',
            name='authorized',
            field=models.ManyToManyField(to='rcallocation.Site'),
        ),
        migrations.AddField(
            model_name='zone',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rcallocation.Site'),
        ),
    ]
