# Generated by Django 1.11.11 on 2019-10-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rcallocation', '0036_sites_and_approvers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocationrequest',
            name='requested_allocation_home',
        ),
        migrations.AlterField(
            model_name='allocationrequest',
            name='geographic_requirements',
            field=models.TextField(
                blank=True,
                help_text='Indicate to the allocations committee any special\n                geographic requirements that you may need; e.g. to run\n                at a specific node or at multiple nodes.  Please \n                include your reasons for these requirements.',
                max_length=1024,
                verbose_name='Special location requirements',
            ),
        ),
    ]
