# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-22 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcallocation', '0036_sites_and_approvers'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationrequest',
            name='associated_site',
            field=models.ForeignKey(blank=True, help_text='The Nectar site that is primarily associated\n        with this allocation.  Under normal circumstances, this will\n        be the site whose approver has most recently approved the\n        allocation', null=True, on_delete=django.db.models.deletion.PROTECT, to='rcallocation.Site'),
        ),
        migrations.AddField(
            model_name='allocationrequest',
            name='national',
            field=models.BooleanField(default=False, help_text='If true, this indicates that the allocation\n        was most recently assessed as meeting the criteria for Nectar\n        National funding', verbose_name='National funding'),
        ),
    ]
