# Generated by Django 1.11.11 on 2019-11-21 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('rcallocation', '0037_remove_requested_allocation_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationrequest',
            name='associated_site',
            field=models.ForeignKey(
                blank=True,
                help_text='The Nectar site that is primarily associated\n        with this allocation.  Under normal circumstances, this will\n        be the site whose approver has most recently approved the\n        allocation',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='rcallocation.Site',
            ),
        ),
        migrations.AddField(
            model_name='allocationrequest',
            name='national',
            field=models.BooleanField(
                default=False,
                help_text='If true, this indicates that the allocation\n        was most recently assessed as meeting the criteria for Nectar\n        National funding',
                verbose_name='National funding',
            ),
        ),
        migrations.AlterField(
            model_name='allocationrequest',
            name='geographic_requirements',
            field=models.TextField(
                blank=True,
                help_text='Indicate to the allocations committee any special\n                geographic requirements that you may need; e.g. to run\n                at a specific node or at multiple nodes.  Please\n                include your reasons for these requirements.',
                max_length=1024,
                verbose_name='Special location requirements',
            ),
        ),
    ]
