# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-03 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcallocation', '0039_populate-national-and-associated-site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocationrequest',
            name='allocation_home',
        ),
    ]
