# Generated by Django 1.11.11 on 2020-02-03 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rcallocation', '0040_remove_allocation_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='first_year_funded',
            field=models.IntegerField(
                error_messages={
                    'max_value': 'Please input a year between 1970 ~ 3000',
                    'min_value': 'Please input a year between 1970 ~ 3000',
                },
                help_text='Specify the first year funded',
                validators=[
                    django.core.validators.MinValueValidator(1970),
                    django.core.validators.MaxValueValidator(3000),
                ],
                verbose_name='First year funded',
            ),
        ),
        migrations.AlterField(
            model_name='grant',
            name='last_year_funded',
            field=models.IntegerField(
                error_messages={
                    'max_value': 'Please input a year between 1970 ~ 3000',
                    'min_value': 'Please input a year between 1970 ~ 3000',
                },
                help_text='Specify the last year funded',
                validators=[
                    django.core.validators.MinValueValidator(1970),
                    django.core.validators.MaxValueValidator(3000),
                ],
                verbose_name='Last year funded',
            ),
        ),
    ]
