# Generated by Django 1.11.11 on 2020-03-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rcallocation', '0041_remove_grant_default_funded_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationrequest',
            name='ncris_support',
            field=models.CharField(
                blank=True,
                help_text='List any NCRIS facilities where the facility\n        management supports this request in furtherance of its goals.\n        For example, the requested resources may enable a project\n        that the NCRIS facility is funding, or they may enable the\n        provision of infrastructure for the facility.',
                max_length=255,
                verbose_name='List NCRIS capabilities supporting this request',
            ),
        ),
        migrations.AlterField(
            model_name='allocationrequest',
            name='nectar_support',
            field=models.CharField(
                blank=True,
                help_text="List any ongoing projects that 1) are or were\n        funded by ARDC or its predecessors (ANDS, Nectar, or RDS),\n        and 2) where the project's management supports this request\n        in furtherance of its goals, and 3) where this allocation\n        will provide resources that benefit the project.",
                max_length=255,
                verbose_name='List any ARDC (or ANDS, Nectar, or RDS) funded projects\n        supporting this request.',
            ),
        ),
        migrations.AlterField(
            model_name='grant',
            name='grant_type',
            field=models.CharField(
                choices=[
                    ('arc', 'Australian Research Council'),
                    ('nhmrc', 'NHMRC'),
                    ('comp', 'Other Australian Competitive Grants'),
                    ('ncris', 'NCRIS funding'),
                    ('ands_nectar_rds', 'Funded by ARDC, Nectar, ANDS or RDS'),
                    ('govt', 'Other Australian government grant'),
                    ('industry', 'Industry funding'),
                    ('ext', 'Other external funding'),
                    ('inst', 'Institutional research grant'),
                ],
                default='arc',
                help_text='Choose the grant type from the dropdown options.',
                max_length=128,
                verbose_name='Type',
            ),
        ),
    ]
