# Generated by Django 1.11.11 on 2020-10-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rcallocation', '0044_for_choices_fixup'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='doi',
            field=models.CharField(
                blank=True,
                help_text='Please provide the DOI for this research output\n                where available.  DOIs for traditional publications should\n                be considered as mandatory.',
                max_length=256,
                null=True,
                verbose_name='Digital Object Identifier (DOI)',
            ),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication',
            field=models.CharField(
                help_text='Please provide any traditional and non-traditional\n                research outputs using a citation style text reference\n                for each. eg. include article/title, journal/outlet, year,\n                DOI/link if available.\n                for each. eg. include article/title, journal/outlet\n                and year.',
                max_length=512,
                verbose_name='Publication/Output',
            ),
        ),
    ]
