# Generated by Django 1.11.11 on 2020-11-30 07:11

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):
    dependencies = [
        ('rcallocation', '0045_add_publication_doi_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationrequest',
            name='managed',
            field=models.BooleanField(
                default=True,
                help_text='Whether the allocation is managed through the dashboard',
            ),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(
                blank=True,
                help_text="Provide the research output's DOI.  For example:\n               '10.23456/more-stuff'.  A DOI is mandatory for peer-reviewed\n               publications.",
                max_length=256,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid DOI.  A DOI looks like\n                                      '10.<digits>/<characters>' with\n                                      the restriction that there are no\n                                      whitespace or control chars in\n                                      <characters>",
                        regex=re.compile(
                            '^10.\\d{4,9}/[^\x00-\x1f\x7f-\x9f\\s]+$', 32
                        ),
                    )
                ],
                verbose_name='Digital Object Identifier (DOI)',
            ),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication',
            field=models.CharField(
                help_text='Provide a citation style text reference\n                for this research output; e.g. include article/title,\n                journal/outlet and year.',
                max_length=512,
                verbose_name='Publication/Output',
            ),
        ),
    ]
