# Generated by Django 1.11.11 on 2020-11-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rcallocation', '0046_minor_wording_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='grant_type',
            field=models.CharField(
                choices=[
                    ('arc', 'Australian Research Council'),
                    ('nhmrc', 'NHMRC'),
                    ('comp', 'Other Australian Competitive Grants'),
                    ('govt', 'Other Australian government grant'),
                    ('industry', 'Industry funding'),
                    ('ext', 'Other external funding'),
                    ('inst', 'Institutional research grant'),
                ],
                default='arc',
                help_text='Choose the grant type from the dropdown options.',
                max_length=128,
                verbose_name='Type',
            ),
        ),
    ]
