# Generated by Django 1.11.29 on 2021-01-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rcallocation', '0048_expunge_ncris_ardc_grants'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='grant_subtype',
            field=models.CharField(
                choices=[
                    ('arc-discovery', 'ARC Discovery project'),
                    ('arc-indigenous', 'ARC Discovery Indigenous'),
                    (
                        'arc-decra',
                        'ARC Discovery Early Career Researcher Award',
                    ),
                    ('arc-future', 'ARC Future Fellowship'),
                    ('arc-laureate', 'ARC Laureate Fellowship'),
                    (
                        'arc-itrp',
                        'ARC Industry Transformation Research Program',
                    ),
                    ('arc-linkage', 'ARC Linkage Project'),
                    ('arc-coe', 'ARC Centre of Excellence'),
                    (
                        'arc-lief',
                        'ARC Linkage Infrastructure Equipment and Facilities',
                    ),
                    ('arc-sri', 'ARC Special Research Initiative'),
                    (
                        'arc-llasp',
                        'ARC Linkage Learned Academies Special Project',
                    ),
                    ('arc-other', 'Other ARC grant'),
                    ('nhmrc-investigator', 'NHMRC Investigator grant'),
                    ('nhmrc-synergy', 'NHMRC Synergy grant'),
                    ('nhmrc-ideas', 'NHMRC Ideas grant'),
                    ('nhmrc-strategic', 'NHMRC Strategic or Leverage grant'),
                    ('nhmrc-program', 'NHMRC Program grant'),
                    ('nhmrc-project', 'NHMRC Project grant'),
                    ('nhmrc-fas', 'NHMRC Fellowship or Scholarship (various)'),
                    ('nhmrc-core', 'NHMRC Center of Research Excellence'),
                    ('nhmrc-development', 'NHMRC Development grant'),
                    ('nhmrc-equipment', 'NHMRC Equipment grant'),
                    (
                        'nhmrc-ctcs',
                        'NHMRC Clinical Trial and Cohort Studies grant',
                    ),
                    (
                        'nhmrc-ics',
                        'NHMRC International Collaborations (various)',
                    ),
                    ('nhmrc-pc', 'NHMRC Partnership Centre'),
                    ('nhmrc-pp', 'NHMRC Partnership project'),
                    ('nhmrc-tcr', 'NHMRC Targeted Calls for Research'),
                    (
                        'nhmrc-iriiss',
                        'NHMRC Independent Research Institute Infrastructure Support Scheme',
                    ),
                    (
                        'nhmrc-bdri',
                        'NHMRC Boosting Dementia Research Initiatives (various)',
                    ),
                    ('nhmrc-other', 'Other NHMRC scheme'),
                    ('act', 'Australian Capital Territory Govt funding'),
                    ('nsw', 'New South Wales Govt funding'),
                    ('nt', 'Northern Territory Govt funding'),
                    ('qld', 'Queensland Govt funding'),
                    ('sa', 'South Australia Govt funding'),
                    ('tas', 'Tasmania Govt funding'),
                    ('vic', 'Victoria Govt funding'),
                    ('wa', 'Western Australia Govt funding'),
                    ('unspecified', 'unspecified'),
                ],
                help_text="Choose an applicable grant subtype from the\n                  dropdown options.  If no option is applicable,\n                  choose 'unspecified' and then fill in the 'Other\n                  funding source details' field below.",
                max_length=128,
                verbose_name='Grant Subtype',
            ),
        ),
        migrations.AlterField(
            model_name='grant',
            name='funding_body_scheme',
            field=models.CharField(
                blank=True,
                help_text='For example, details of a state government\n                  grant scheme, or an industry funding source.',
                max_length=255,
                verbose_name='Other funding source details',
            ),
        ),
        migrations.AlterField(
            model_name='grant',
            name='grant_type',
            field=models.CharField(
                choices=[
                    ('arc', 'Australian Research Council'),
                    ('nhmrc', 'NHMRC'),
                    (
                        'comp',
                        'Other Australian Federal Govt competitive grant',
                    ),
                    (
                        'govt',
                        'Australian Federal Govt non-competitive funding',
                    ),
                    ('state', 'Australian State / Territory Govt funding'),
                    ('industry', 'Industry funding'),
                    ('ext', 'Other external funding'),
                    ('inst', 'Institutional research funding'),
                    ('nz', 'New Zealand research funding'),
                ],
                help_text='Choose the grant type from the dropdown options.',
                max_length=128,
                verbose_name='Grant Type',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='grant',
            unique_together=set(
                [
                    (
                        'allocation',
                        'grant_type',
                        'grant_subtype',
                        'funding_body_scheme',
                        'grant_id',
                        'first_year_funded',
                        'total_funding',
                    )
                ]
            ),
        ),
    ]
