# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-04 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcallocation', '0048_expunge_ncris_ardc_grants'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationrequest',
            name='research_use_case',
            field=models.TextField(blank=True, help_text='Provide a brief overview of your research project.', max_length=4096, verbose_name='Research use case'),
        ),
        migrations.AlterField(
            model_name='allocationrequest',
            name='use_case',
            field=models.TextField(help_text='Explain how you will use the Research Cloud to \n        support your project.', max_length=4096, verbose_name='Justification for use of Research Cloud'),
        ),
    ]
