# Generated by Django 1.11.29 on 2021-01-18 04:50


import re

from django.db import migrations


class Migration(migrations.Migration):
    def backfill_arc_subtypes(apps, schema_editor):
        Grant = apps.get_model('rcallocation', 'Grant')
        ARC_GRANT_ID = re.compile('([A-Z]{2})[0-9]+')
        for grant in Grant.objects.all():
            if (
                grant.grant_type == 'arc'
                and grant.grant_subtype in ['', 'unspecified']
                and grant.grant_id
            ):
                match = re.fullmatch(ARC_GRANT_ID, grant.grant_id)
                if not match:
                    continue
                code = match.group(1)
                if code == 'IN':
                    grant.grant_subtype = 'arc-indigenous'
                elif code == 'DP':
                    grant.grant_subtype = 'arc-discovery'
                elif code == 'DE':
                    grant.grant_subtype = 'arc-decra'
                elif code == 'LE':
                    grant.grant_subtype = 'arc-lief'
                elif code == 'LP':
                    grant.grant_subtype = 'arc-linkage'
                elif code == 'FL':
                    grant.grant_subtype = 'arc-laureate'
                elif code == 'FT':
                    grant.grant_subtype = 'arc-future'
                elif code == 'CE':
                    grant.grant_subtype = 'arc-coe'
                elif code == 'SR':
                    grant.grant_subtype = 'arc-sri'
                elif code in ['IH', 'IC']:
                    grant.grant_subtype = 'arc-itrp'
                else:
                    grant.grant_subtype = 'arc-other'
                grant.save()

    dependencies = [
        ('rcallocation', '0049_add_grant_subtype'),
    ]

    operations = [
        migrations.RunPython(
            backfill_arc_subtypes,
            # This is not strictly correct.  However
            # reversing migration 0049 removes the
            # grant_subtype field entirely.  That'll do it.
            reverse_code=migrations.RunPython.noop,
        )
    ]
