# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-03 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcallocation', '0050_backfill_arc_grant_subtypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageSurveyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(help_text='The usage type to displayed to the user', max_length=128, verbose_name='Usage Type')),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsageSurveyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField()),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='rcallocation.AllocationRequest')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rcallocation.UsageSurveyQuestion')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usagesurveyresponse',
            unique_together=set([('allocation', 'question')]),
        ),
    ]
