# Generated by Django 1.11.29 on 2021-02-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rcallocation', '0050_backfill_arc_grant_subtypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageType',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=40, verbose_name='Usage Type'),
                ),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='allocationrequest',
            name='usage_types',
            field=models.ManyToManyField(to='rcallocation.UsageType'),
        ),
    ]
