# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-03 04:58
from __future__ import unicode_literals

from django.db import migrations


INITIAL_QUESTIONS = [
    'Hosting services to support research',
    'Collaboration platform',
    'Hosting a website',
    'Hosting a database',
    'Hosting and sharing data',
    'Collaborating with other institutions',
    'Collaborating internationally',
    'Machine learning',
    'Data analysis',
    'Modelling and simulation',
    'Other',
]


class Migration(migrations.Migration):
    
    def addQuestions(apps, schema_editor):
        UsageSurveyQuestion = apps.get_model('rcallocation',
                                             'UsageSurveyQuestion')
        for utype in INITIAL_QUESTIONS:
            UsageSurveyQuestion.objects.create(
                usage_type=utype, enabled=True)

    def removeQuestions(apps, schema_editor):
        UsageSurveyQuestion = apps.get_model('rcallocation',
                                             'UsageSurveyQuestion')
        UsageSurveyQuestion.objects.all().delete();

    dependencies = [
        ('rcallocation', '0051_add_usage_surveys'),
    ]

    operations = [
        migrations.RunPython(addQuestions, removeQuestions)
    ]
