# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-03 04:58
from __future__ import unicode_literals

from django.db import migrations


INITIAL_QUESTIONS = [
    ('Hosting services to support research', False),
    ('Collaboration platform', False),
    ('Hosting a website', False),
    ('Hosting a database', False),
    ('Hosting and sharing data', False),
    ('Collaborating with other institutions', False),
    ('Collaborating internationally', False),
    ('Machine learning', False),
    ('Data analysis', False),
    ('Modelling and simulation', False),
    ('Other', True),
]


class Migration(migrations.Migration):
    
    def addQuestions(apps, schema_editor):
        UsageSurveyQuestion = apps.get_model('rcallocation',
                                             'UsageSurveyQuestion')
        for (utype, details) in INITIAL_QUESTIONS:
            UsageSurveyQuestion.objects.create(
                usage_type=utype, enabled=True, allow_details=details)

    def removeQuestions(apps, schema_editor):
        UsageSurveyQuestion = apps.get_model('rcallocation',
                                             'UsageSurveyQuestion')
        UsageSurveyQuestion.objects.all().delete();

    dependencies = [
        ('rcallocation', '0051_add_usage_surveys'),
    ]

    operations = [
        migrations.RunPython(addQuestions, removeQuestions)
    ]
