# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-03 04:58
from __future__ import unicode_literals

from django.db import migrations


INITIAL_QUESTIONS = [
    ('service', 'Hosting services to support research', False),
    ('collab_platform', 'Collaboration platform', False),
    ('website', 'Hosting a website', False),
    ('database', 'Hosting a database', False),
    ('data_sharing', 'Hosting and sharing data', False),
    ('collab_cross_institution',
     'Collaborating with other institutions', False),
    ('collab_international', 'Collaborating internationally', False),
    ('machine_learning', 'Machine learning', False),
    ('data_anaysis', 'Data analysis', False),
    ('modelling', 'Modelling and simulation', False),
    ('other', 'Other', True),
]


class Migration(migrations.Migration):
    
    def addQuestions(apps, schema_editor):
        UsageSurveyQuestion = apps.get_model('rcallocation',
                                             'UsageSurveyQuestion')
        for (tag, utype, details) in INITIAL_QUESTIONS:
            UsageSurveyQuestion.objects.create(
                tag=tag, usage_type=utype, usage_explanation="",
                enabled=True, allow_details=details)

    def removeQuestions(apps, schema_editor):
        UsageSurveyQuestion = apps.get_model('rcallocation',
                                             'UsageSurveyQuestion')
        UsageSurveyQuestion.objects.all().delete();

    dependencies = [
        ('rcallocation', '0051_add_usage_surveys'),
    ]

    operations = [
        migrations.RunPython(addQuestions, removeQuestions)
    ]
