# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-09 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcallocation', '0055_wording_changes'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCRISFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Full NCRIS facility name')),
                ('short_name', models.CharField(max_length=200, unique=True, verbose_name='Common short name or acronym')),
            ],
        ),
        migrations.AddField(
            model_name='allocationrequest',
            name='ncris_facilities',
            field=models.ManyToManyField(blank=True, to='rcallocation.NCRISFacility'),
        ),
    ]
