# Generated by Django 1.11.29 on 2021-05-11 04:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rcallocation', '0055_wording_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='quota',
            field=models.IntegerField(
                default='0',
                validators=[django.core.validators.MinValueValidator(-1)],
                verbose_name='Allocated quota',
            ),
        ),
        migrations.AlterField(
            model_name='quota',
            name='requested_quota',
            field=models.IntegerField(
                default='0',
                validators=[django.core.validators.MinValueValidator(-1)],
                verbose_name='Requested quota',
            ),
        ),
    ]
