# Generated by Django 1.11.29 on 2021-04-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rcallocation', '0056_support_unlimited_quota'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCRISFacility',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=200,
                        unique=True,
                        verbose_name='Full NCRIS facility name',
                    ),
                ),
                (
                    'short_name',
                    models.CharField(
                        max_length=200,
                        unique=True,
                        verbose_name='Common short name or acronym',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='allocationrequest',
            name='ncris_explanation',
            field=models.CharField(
                blank=True,
                help_text='Explain how each listed NCRIS Facility supports or is\n        supported by this request.',
                max_length=1024,
                verbose_name='NCRIS Support explanation',
            ),
        ),
        migrations.AlterField(
            model_name='publication',
            name='output_type',
            field=models.CharField(
                choices=[
                    (None, 'Select an output type'),
                    ('AJ', 'Peer reviewed journal article'),
                    ('AP', 'Other peer reviewed paper'),
                    ('AN', 'Non-peer reviewed paper'),
                    ('B', 'Book or book chapter'),
                    ('M', 'Media publication'),
                    ('D', 'Dataset'),
                    ('S', 'Software'),
                    ('P', 'Patent'),
                    ('O', 'Other'),
                    ('U', 'Unspecified'),
                ],
                help_text="Select a publication type that best describes\n                the publication.  The 'Media publication' type is\n                intended to encompass traditional media and 'new'\n                media such as websites, blogs and social media.",
                max_length=2,
                verbose_name='Research Output type',
            ),
        ),
        migrations.AddField(
            model_name='allocationrequest',
            name='ncris_facilities',
            field=models.ManyToManyField(
                blank=True, to='rcallocation.NCRISFacility'
            ),
        ),
    ]
