# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-11 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcallocation', '0057_populate_ncris_facilities'),
    ]

    operations = [
    ]
