# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-07 05:22
from __future__ import unicode_literals

from django.db import migrations

# This list needs review
INITIAL_PROGRAMS = [
    ("ARDC Platforms", "ARDC Platforms program"),
    ("ARDC NDA", "ARDC National Data Assets program"),
    ("ARDC TRDC", "ARDC Translational Research Data Challenges program"),
    ("ARDC Internal", "ARDC Internal projects"),
    ("ARDC Other", "Other ARDC-supported projects"),
    ("Nectar VL", "Nectar Virual Laboratory program"),
    ("Nectar DeVL", "Nectar Data enhanced Virual Laboratory program"),
    ("Nectar Other", "Other Nectar supported projects"),
    ("ANDS", "ANDS supported projects"),
    ("RDS / RDSI", "RDS / RDSI supported projects"),
]

# This list needs completion
INITIAL_PROJECTS = [
    ("CVL", "Characterization Virtual Laboratory"),
    ("GVL", "Genomics Virtual Laboratory"),
    ("BCCVL", "Biodiversity and Climate Change Virtual Laboratory"),
]


class Migration(migrations.Migration):

    def addARDCSupport(apps, schema_editor):
        ARDCSupport = apps.get_model('rcallocation', 'ARDCSupport')
        for p in INITIAL_PROGRAMS:
            ARDCSupport.objects.create(
                name=p[0], short_name=p[1],
                project=False, explain=True)
        for p in INITIAL_PROJECTS:
            ARDCSupport.objects.create(
                name=p[0], short_name=p[1])

    def removeARDCSupport(apps, schema_editor):
        ARDCSupport = apps.get_model('rcallocation', 'ARDCSupport')
        ARDCSupport.objects.all().delete()

    dependencies = [
        ('rcallocation', '0059_add_ardc_support'),
    ]

    operations = [
        migrations.RunPython(addARDCSupport, removeARDCSupport)
    ]
