# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-07 05:22
from __future__ import unicode_literals

from django.db import migrations

# This list needs review
INITIAL_PROGRAMS = [
    # Platforms initiative
    ("Platforms", "Platforms program"),
    ("DR", "Data retention program"),
    # National Data Assets initiative
    ("CN-NDA", "Cross-NCRIS National Data Assets program"),
    ("ADP", "Australian Data Partnerships program"),
    ("PSB", "Public Sector Bridges program"),
    ("EC", "Emerging Collections program"),
    ("IU", "Institutional Underpinnings program"),
    ("HSANDA", "Health Studies Australian National Data Assets program"),
    # Translational Research Data Challenges initiative
    ("BDC", "Bushfire Data Challenges program"),
    # Current but unclassified
    ("ARDC Internal", "ARDC Internal projects"),
    ("ARDC Nectar", "ARDC Nectar cloud operations"),
    # Old programs
    ("Nectar VL", "Nectar Virual Laboratory program"),
    ("Nectar DeVL", "Nectar Data enhanced Virual Laboratory program"),
    ("Nectar Other", "Other Nectar supported projects"),
    ("ANDS", "ANDS supported projects"),
    ("RDS / RDSI", "RDS / RDSI supported projects"),
]

# This list needs completion
INITIAL_PROJECTS = [
    # Platforms projects
    ("Air-Health SWS",
     "Scientific workflow system for environmental health impact assessments",
     "PL059"),
    ("TLCMap 2.0",
     "Time-Layered Cultural Map of Australia 2.0",
     "PL069"),
    ("E2AMLBD",
     "Environments to Accelerate Machine Learning Based Discovery",
     "PL107"),
    ("AIS",
     "An Australian Imaging Service: Melding the Clinical and Academic "
     "using a Distributed Federation of Enhanced XNATS",
     "PL102"),
    ("GMRT—AusSeabed",
     "Global Multi-Resolution Topography for Australian coastal and "
     "ocean models",
     "PL019"),
    ("FishID", "Transforming Australian aquatic ecosystem monitoring "
     "using AI",
     "PL071"),
    ("Open EcoAcoustics",
     "Open EcoAcoustics: A Platform to Manage, Share and Analyse "
     "Ecoacoustic Data",
     "PL050"),
    ("VARDC",
     "Veterinary and Animal Research Data Commons",
     "PL073"),
    ("EcoCommons", "EcoCommons Australia", "PL108"),
    ("AgReFed",
     "AgReFed: A platform for the transformation of agricultural research",
     "PL005"),
    ("AHDAP", "The Australian Housing Data Analytics Platform", "PL065"),
    ("Australian Cancer Data Network",
     "Australian Cancer Data Network: distributed learning from "
     "clinical data",
     "PL014"),
    ("AEDAPT",
     "Australian Electrophysiology Data Analytics PlaTform",
     "PL017"),
    ("Human Genomes Platform",
     "Global technologies and standards for sharing human genomics "
     "research data",
     "PL032"),
    ("G-ADOPT", "Geodynamic ADjoint Optimization PlaTform", "PL031"),
    ("Biosecurity Commons",
     "Biosecurity Commons - Intelligently Managing our Pests and Diseases",
     "PL021"),
    ("Secure eResearch Platform",
     "Scalable Governance, Control & Management of FAIR Sensitive "
     "Research Data",
     "PL058"),
    ("ATAP", "Australian Text Analytics Platform", "PL074"),
    ("Australian Digital Observatory",
     "Australian Digital Observatory: Infrastructure for Dynamic Digital Data",
     "PL015"),
    ("ACCS", "The Australian Characterisation Commons at Scale", "PL101"),
    ("ASDC", "Establishing Australia's Scalable Done Cloud (ASDC)", "PL103"),
    ("ERICA",
     "E-Research Institutional Cloud Architecture (ERICA): "
     "Secure cloud computing for sensitive microdata",
     "PL109"),
    ("FAIMS 3.0",
     "FAIMS 3.0 Electronic Field Notebooks: A Platform for field research "
     "supporting digital capture and management in diverse situations",
     "PL110"),
    ("BioCommons BYOD",
     "The BioCommons BYOD Expansion Project "
     "(Integrating instruments, analysis tools and compute platforms for "
     "leadership bioinformatics",
     "PL105"),
    ("ATRC", "The Australian Transport Research Cloud (ATRC)", "PL104"),
    ("CADRE",
     "Coordinated Access for Data, Researchers and Environments (CADRE) "
     "- A Five Safes Implementation Framework for Sensitive Data in HASS",
     "PL106"),
    # Virtual Laboratory projects
    ("Alveo", "A Virtual Lab for Human Communication Science"),
    ("ASVO", "All-Sky Virtual Observatory"),
    ("BCCVL", "Biodiversity and Climate Change Virtual Laboratory"),
    ("CVL", "Characterization Virtual Laboratory"),
    ("CWSLab", "Climate and Weather Science Lab"),
    ("FAIMS", "Field Acquired Information Management Systems"),
    ("GVL", "Genomics Virtual Laboratory"),
    ("HuNI", "Humanities Networked Infrastructure"),
    ("IEL", "Industrial Ecology Lab"),
]


class Migration(migrations.Migration):

    def addARDCSupport(apps, schema_editor):
        ARDCSupport = apps.get_model('rcallocation', 'ARDCSupport')
        for p in INITIAL_PROGRAMS:
            ARDCSupport.objects.create(
                name=p[1], short_name=p[0],
                project=False, explain=True)
        for p in INITIAL_PROJECTS:
            if len(p) == 3:
                ARDCSupport.objects.create(
                    name=p[0], short_name=p[2])
            else:
                ARDCSupport.objects.create(
                name=p[1], short_name=p[0])

    def removeARDCSupport(apps, schema_editor):
        ARDCSupport = apps.get_model('rcallocation', 'ARDCSupport')
        ARDCSupport.objects.all().delete()

    dependencies = [
        ('rcallocation', '0059_add_ardc_support'),
    ]

    operations = [
        migrations.RunPython(addARDCSupport, removeARDCSupport)
    ]
