# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-28 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcallocation', '0060_populate_ardc_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationrequest',
            name='special_approval',
            field=models.CharField(blank=True, help_text='Use this field to record reasons the allocation\n        is approved as National despite not meeting the primary criteria; \n        i.e. a current competitive, NCRIS support or ARDC support.  \n        See the RC-NAS policy for the possible reasons.  This is only\n        visible to allocation admins', max_length=1024, verbose_name='Special RC-NAS approval reasons'),
        ),
    ]
