# Generated by Django 2.2.19 on 2022-02-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rcallocation', '0061_add_special_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
