# Generated by Django 2.2.19 on 2022-04-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rcallocation', '0063_service_type_experimental'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='default',
            field=models.IntegerField(null=True),
        ),
    ]
