# Generated by Django 2.2.19 on 2022-04-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcallocation', '0064_add_resource_default_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetype',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['display_name']},
        ),
        migrations.AlterField(
            model_name='allocationrequest',
            name='special_approval',
            field=models.CharField(blank=True, help_text='Use this field to record reasons the allocation\n        is approved as National despite not meeting the primary criteria;\n        i.e. a current competitive, NCRIS support or ARDC support.\n        See the RC-NAS policy for the possible reasons.  This is only\n        visible to allocation admins', max_length=1024, verbose_name='Special RC-NAS approval reasons'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='grant_subtype',
            field=models.CharField(choices=[(None, 'Select a grant subtype'), ('arc-discovery', 'ARC Discovery project'), ('arc-indigenous', 'ARC Discovery Indigenous'), ('arc-decra', 'ARC Discovery Early Career Researcher Award'), ('arc-future', 'ARC Future Fellowship'), ('arc-laureate', 'ARC Laureate Fellowship'), ('arc-itrp', 'ARC Industry Transformation Research Program'), ('arc-linkage', 'ARC Linkage Project'), ('arc-coe', 'ARC Centre of Excellence'), ('arc-lief', 'ARC Linkage Infrastructure Equipment and Facilities'), ('arc-sri', 'ARC Special Research Initiative'), ('arc-llasp', 'ARC Linkage Learned Academies Special Project'), ('arc-other', 'Other ARC grant'), ('nhmrc-investigator', 'NHMRC Investigator grant'), ('nhmrc-synergy', 'NHMRC Synergy grant'), ('nhmrc-ideas', 'NHMRC Ideas grant'), ('nhmrc-strategic', 'NHMRC Strategic or Leverage grant'), ('nhmrc-program', 'NHMRC Program grant'), ('nhmrc-project', 'NHMRC Project grant'), ('nhmrc-fas', 'NHMRC Fellowship or Scholarship (various)'), ('nhmrc-core', 'NHMRC Center of Research Excellence'), ('nhmrc-development', 'NHMRC Development grant'), ('nhmrc-equipment', 'NHMRC Equipment grant'), ('nhmrc-ctcs', 'NHMRC Clinical Trial and Cohort Studies grant'), ('nhmrc-ics', 'NHMRC International Collaborations (various)'), ('nhmrc-pc', 'NHMRC Partnership Centre'), ('nhmrc-pp', 'NHMRC Partnership project'), ('nhmrc-tcr', 'NHMRC Targeted Calls for Research'), ('nhmrc-iriiss', 'NHMRC Independent Research Institute Infrastructure Support Scheme'), ('nhmrc-bdri', 'NHMRC Boosting Dementia Research Initiatives (various)'), ('nhmrc-other', 'Other NHMRC scheme'), ('rdc-wa', 'Wine Australia'), ('rdc-crdc', 'Cotton RDC'), ('rdc-frdc', 'Fisheries RDC'), ('rdc-grdc', 'Grains RDC'), ('rdc-agrifutures', 'Rural Industries RDC (AgriFutures Australia)'), ('rdc-ael', 'Australian Eggs Ltd'), ('rdc-livecorp', 'Australian Livestock Export Corp Ltd (LiveCorp)'), ('rdc-ampc', 'Australian Meat Processor Corp'), ('rdc-apl', 'Australian Pork Ltd'), ('rdc-awil', 'Australian Wool Innovation Ltd'), ('rdc-dal', 'Dairy Australia Ltd'), ('rdc-fwpa', 'Forest and Wood Products Australia'), ('rdc-hial', 'Horticulture Innovation Australia Ltd'), ('rdc-mla', 'Meat and Livestock Australia'), ('rdc-sral', 'Sugar Research Australia Ltd'), ('act', 'Australian Capital Territory Govt funding'), ('nsw', 'New South Wales Govt funding'), ('nt', 'Northern Territory Govt funding'), ('qld', 'Queensland Govt funding'), ('sa', 'South Australia Govt funding'), ('tas', 'Tasmania Govt funding'), ('vic', 'Victoria Govt funding'), ('wa', 'Western Australia Govt funding'), ('unspecified', 'unspecified')], help_text="Choose an applicable grant subtype from the\n                  dropdown options.  If no option is applicable,\n                  choose 'unspecified' and then fill in the 'Other\n                  funding source details' field below.", max_length=128, verbose_name='Grant Subtype'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='grant_type',
            field=models.CharField(choices=[(None, 'Select a grant type'), ('arc', 'Australian Research Council'), ('nhmrc', 'NHMRC'), ('rdc', 'Rural Research and Development Corporation'), ('comp', 'Other Australian Federal Govt competitive grant'), ('govt', 'Australian Federal Govt non-competitive funding'), ('state', 'Australian State / Territory Govt funding'), ('industry', 'Industry funding'), ('ext', 'Other external funding'), ('inst', 'Institutional research funding'), ('nz', 'New Zealand research funding')], help_text='Choose the grant type from the dropdown options.', max_length=128, verbose_name='Grant Type'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='default',
            field=models.IntegerField(help_text='This is used to set an initial value on quota forms if no quota is requested. Will also be used if existing is less than this', null=True),
        ),
    ]
