# Generated by Django 2.2.19 on 2022-08-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcallocation', '0065_auto_20220427_0027'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='allocationrequest',
            index=models.Index(fields=['project_id'], name='rcallocatio_project_479f7e_idx'),
        ),
        migrations.AddIndex(
            model_name='allocationrequest',
            index=models.Index(fields=['status'], name='rcallocatio_status_94501a_idx'),
        ),
    ]
