# Generated by Django 2.2.12 on 2023-04-11 06:44

from django.conf import settings
from django.db import migrations

from nectar_dashboard.rcallocation.management import catalogs
from nectar_dashboard.rcallocation.management import org_loading


class Migration(migrations.Migration):

    def load_ror_dump(apps, schema_editor):
        catalog = catalogs.make_migration_catalog(apps)
        if settings.ORGANISATION_MIGRATION_ROR_DUMP_URI:
            org_loading.Loader(catalog).load(
                settings.ORGANISATION_MIGRATION_ROR_DUMP_URI, initial=True)

    def clear_organisations(apps, schema_editor):
        catalog = catalogs.make_migration_catalog(apps)
        catalog.Organisation.objects.all().delete()        

    dependencies = [
        ('rcallocation', '0069_add_organisations'),
    ]

    operations = [
        migrations.RunPython(load_ror_dump, clear_organisations)
    ]
