# Generated by Django 2.2.12 on 2023-04-11 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcallocation', '0069_add_organisations'),
    ]

    operations = [
    ]
