# Generated by Django 2.2.12 on 2023-04-11 06:45

from django.conf import settings
from django.db import migrations

from nectar_dashboard.rcallocation.migrations.orgs import catalogs
from nectar_dashboard.rcallocation.migrations.orgs import org_matching


class Migration(migrations.Migration):

    def migrate_organisations(apps, schema_editor):
        catalog = catalogs.make_migration_catalog(apps)
        if settings.ORGANISATION_MIGRATION_ROR_DUMP_URI:
            org_matching.Migrater(catalog).run(
                settings.ORGANISATION_MIGRATION_ROR_DUMP_URI)
            strict = settings.ORGANISATION_MIGRATION_STRICT
            org_matching.backfill(catalog, strict=strict)

    def clear_organisation_references(apps, schema_editor):
        catalog = catalogs.make_migration_catalog(apps)
        for ci in catalog.ChiefInvestigator.objects.all():
            ci.primary_organisation = None
            ci.save()

    dependencies = [
        ('rcallocation', '0070_load_ror_dump'),
    ]

    operations = [
                migrations.RunPython(migrate_organisations,
                                     clear_organisation_references)
    ]
