# Generated by Django 2.2.12 on 2023-04-20 06:40

from django.db import migrations
import django.db.models.deletion
import select2.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rcallocation', '0072_check_institutions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chiefinvestigator',
            name='institution',
        ),
        migrations.AlterField(
            model_name='allocationrequest',
            name='supported_organisations',
            field=select2.fields.ManyToManyField(sorted=False, to='rcallocation.Organisation'),
        ),
        migrations.AlterField(
            model_name='chiefinvestigator',
            name='primary_organisation',
            field=select2.fields.ForeignKey(help_text="The chief investigator's primary organisation.", on_delete=django.db.models.deletion.PROTECT, to='rcallocation.Organisation'),
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
