# Generated by Django 3.2.18 on 2023-11-30 04:40

import logging

from django.db import migrations
import django.db.models.deletion
import select2.fields


LOG = logging.getLogger(__name__)


class Migration(migrations.Migration):
    dependencies = [
        ('rcallocation', '0074_bundles'),
    ]

    def remove_unknown_org_refs(apps, schema_editor):
        ChiefInvestigator = apps.get_model('rcallocation', 'ChiefInvestigator')
        AllocationRequest = apps.get_model('rcallocation', 'AllocationRequest')
        Organisation = apps.get_model('rcallocation', 'Organisation')

        try:
            unknown_org = Organisation.objects.get(short_name='unknown')
        except Organisation.DoesNotExist:
            LOG.info("Unknown org doesn't exist")
            return

        cis = ChiefInvestigator.objects.filter(
            primary_organisation=unknown_org
        )

        for ci in cis:
            ci.primary_organisation = None
            ci.save()

        for a in AllocationRequest.objects.filter(
            supported_organisations=unknown_org
        ):
            a.supported_organisations.remove(unknown_org)
            LOG.info("Remove unknown org from %s", a)

        unknown_org.delete()

    def add_unknown_org_refs(apps, schema_editor):
        ChiefInvestigator = apps.get_model('rcallocation', 'ChiefInvestigator')
        Organisation = apps.get_model('rcallocation', 'Organisation')

        unknown_org, created = Organisation.objects.get_or_create(
            short_name='unknown', full_name='Unspecified Organisation'
        )

        cis = ChiefInvestigator.objects.filter(primary_organisation=None)

        for ci in cis:
            ci.primary_organisation = unknown_org
            ci.save()

    operations = [
        migrations.AlterField(
            model_name='chiefinvestigator',
            name='primary_organisation',
            field=select2.fields.ForeignKey(
                help_text="The chief investigator's primary organisation.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='rcallocation.organisation',
            ),
        ),
        migrations.RunPython(remove_unknown_org_refs, add_unknown_org_refs),
    ]
