# Generated by Django 3.2.18 on 2024-03-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rcallocation', '0076_Add_su_per_year_to_bundle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['full_name']},
        ),
        migrations.AlterField(
            model_name='allocationrequest',
            name='estimated_project_duration',
            field=models.IntegerField(
                choices=[
                    (1, '1-month'),
                    (3, '3-months'),
                    (6, '6-months'),
                    (12, '12-months'),
                ],
                default=12,
                help_text='Resources are approved for at most 12-months,\n                    but projects can extend a request for resources\n                    once it has been approved.',
                verbose_name='Estimated project duration',
            ),
        ),
    ]
