# Generated by Django 3.2.18 on 2025-01-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rcallocation', '0081_auto_20240808_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationrequest',
            name='contact_email',
            field=models.EmailField(
                blank=True,
                help_text='The e-mail address provided by your organisation which\n        will be used to communicate with you about this allocation request.\n        If invalid please contact your organisation and ask them to correct\n        your e-mail address',
                max_length=254,
                verbose_name='Contact e-mail',
            ),
        ),
    ]
