# Generated by Django 3.2.18 on 2025-04-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rcallocation', '0083_update_ncris_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationrequest',
            name='data_classification_level',
            field=models.CharField(
                choices=[
                    ('', 'Please select...'),
                    ('green', 'Green'),
                    ('yellow', 'Yellow'),
                    ('orange', 'Orange'),
                    ('red', 'Red'),
                    ('not_sure', 'Not Sure'),
                ],
                max_length=10,
                null=True,
                verbose_name='Data Classification Level',
            ),
        ),
        migrations.AddField(
            model_name='allocationrequest',
            name='has_sensitive_data',
            field=models.CharField(
                choices=[
                    ('', 'Please select...'),
                    (
                        'no_sensitive',
                        'No, the project does not involve sensitive data.',
                    ),
                    ('sensitive', 'Yes, the project involves sensitive data.'),
                    (
                        'unknown',
                        'I am unsure if my project contains sensitive data.',
                    ),
                ],
                help_text='<a href="https://support.ehelp.edu.au/support/\n                 solutions/articles/6000277743" target="_blank">\n                 Sensitive data</a> is data that can be used to identify\n                 an individual, species, object, process, or location\n                 that introduces a risk of discrimination, harm, or\n                 unwanted attention. Examples could include identifiable\n                 personal and health/medical data, Indigenous data,\n                 ecological data, and commercial-in-confidence data',
                max_length=20,
                null=True,
                verbose_name='Sensitive Data',
            ),
        ),
        migrations.AddField(
            model_name='allocationrequest',
            name='institutional_data_review',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', 'Please select...'),
                    ('yes', 'Yes'),
                    ('not_yet', 'Not yet'),
                ],
                max_length=10,
                null=True,
                verbose_name='Institutional Data Review',
            ),
        ),
    ]
