# Generated by Django 3.2.18 on 2025-05-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rcallocation', '0084_add_data_sensitivity_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationrequest',
            name='has_sensitive_data',
            field=models.CharField(
                choices=[
                    ('', 'Please select...'),
                    (
                        'no_sensitive',
                        'No, the project does not involve sensitive data.',
                    ),
                    ('sensitive', 'Yes, the project involves sensitive data.'),
                    (
                        'unknown',
                        'I am unsure if my project contains sensitive data.',
                    ),
                ],
                max_length=20,
                null=True,
                verbose_name='Sensitive Data',
            ),
        ),
    ]
