# Generated by Django 4.2.19 on 2026-05-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rcallocation', '0085_remove_help_text_data_sensitivity_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='location_specific',
            field=models.BooleanField(default=False),
        ),
    ]
