# Generated by Django 4.2.19 on 2026-06-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rcallocation', '0087_flip_volume_share_location_specific'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='grant_type',
            field=models.CharField(
                choices=[
                    (None, 'Select a grant type'),
                    ('arc', 'Australian Research Council'),
                    ('nhmrc', 'NHMRC'),
                    (
                        'rdc',
                        'Rural Research and Development Corporations (RDCs)',
                    ),
                    (
                        'comp',
                        'Other Australian Federal Govt competitive grant',
                    ),
                    (
                        'govt',
                        'Australian Federal Govt non-competitive funding',
                    ),
                    ('state', 'Australian State / Territory Govt funding'),
                    ('industry', 'Industry funding'),
                    ('ext', 'Other external funding'),
                    ('inst', 'Institutional research funding'),
                    ('nz', 'New Zealand research funding'),
                ],
                help_text='Choose the grant type from the dropdown options.',
                max_length=128,
                verbose_name='Grant Type',
            ),
        ),
    ]
