# Generated by Django 4.2.19 on 2026-07-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rcallocation', '0088_alter_grant_grant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='grant_subtype',
            field=models.CharField(
                choices=[
                    (None, 'Select a grant subtype'),
                    ('arc-discovery', 'ARC Discovery project'),
                    ('arc-indigenous', 'ARC Discovery Indigenous'),
                    (
                        'arc-decra',
                        'ARC Discovery Early Career Researcher Award',
                    ),
                    ('arc-future', 'ARC Future Fellowship'),
                    ('arc-laureate', 'ARC Laureate Fellowship'),
                    (
                        'arc-itrp',
                        'ARC Industry Transformation Research Program',
                    ),
                    ('arc-linkage', 'ARC Linkage Project'),
                    ('arc-coe', 'ARC Centre of Excellence'),
                    (
                        'arc-lief',
                        'ARC Linkage Infrastructure Equipment and Facilities',
                    ),
                    ('arc-sri', 'ARC Special Research Initiative'),
                    (
                        'arc-llasp',
                        'ARC Linkage Learned Academies Special Project',
                    ),
                    ('arc-other', 'Other ARC grant'),
                    ('nhmrc-investigator', 'NHMRC Investigator grant'),
                    ('nhmrc-synergy', 'NHMRC Synergy grant'),
                    ('nhmrc-ideas', 'NHMRC Ideas grant'),
                    ('nhmrc-strategic', 'NHMRC Strategic or Leverage grant'),
                    ('nhmrc-program', 'NHMRC Program grant'),
                    ('nhmrc-project', 'NHMRC Project grant'),
                    ('nhmrc-fas', 'NHMRC Fellowship or Scholarship (various)'),
                    ('nhmrc-core', 'NHMRC Center of Research Excellence'),
                    ('nhmrc-development', 'NHMRC Development grant'),
                    ('nhmrc-equipment', 'NHMRC Equipment grant'),
                    (
                        'nhmrc-ctcs',
                        'NHMRC Clinical Trial and Cohort Studies grant',
                    ),
                    (
                        'nhmrc-ics',
                        'NHMRC International Collaborations (various)',
                    ),
                    ('nhmrc-mrff', 'NHMRC Medical Research Future Fund'),
                    ('nhmrc-pc', 'NHMRC Partnership Centre'),
                    ('nhmrc-pp', 'NHMRC Partnership project'),
                    ('nhmrc-tcr', 'NHMRC Targeted Calls for Research'),
                    (
                        'nhmrc-iriiss',
                        'NHMRC Independent Research Institute Infrastructure Support Scheme',
                    ),
                    (
                        'nhmrc-bdri',
                        'NHMRC Boosting Dementia Research Initiatives (various)',
                    ),
                    ('nhmrc-other', 'Other NHMRC scheme'),
                    (
                        'mrff-brain-cancer',
                        'MRFF Australian Brain Cancer Mission',
                    ),
                    (
                        'mrff-cardiovascular',
                        'MRFF Cardiovascular Health Mission',
                    ),
                    ('mrff-clinical-trials', 'MRFF Clinical Trials Activity'),
                    (
                        'mrff-clinician-researchers',
                        'MRFF Clinician Researchers',
                    ),
                    ('mrff-coronavirus', 'MRFF Coronavirus Research Response'),
                    (
                        'mrff-dementia-ageing',
                        'MRFF Dementia, Ageing and Aged Care Mission',
                    ),
                    ('mrff-emcr', 'MRFF Early to Mid-Career Researchers'),
                    (
                        'mrff-epcdr',
                        'MRFF Emerging Priorities and Consumer Driven Research',
                    ),
                    (
                        'mrff-frontier',
                        'MRFF Frontier Health and Medical Research',
                    ),
                    ('mrff-genomics', 'MRFF Genomics Health Futures Mission'),
                    ('mrff-global-health', 'MRFF Global Health'),
                    (
                        'mrff-indigenous',
                        'MRFF Indigenous Health Research Fund',
                    ),
                    (
                        'mrff-commercialisation',
                        'MRFF Medical Research Commercialisation',
                    ),
                    (
                        'mrff-million-minds',
                        'MRFF Million Minds Mental Health Research Mission',
                    ),
                    (
                        'mrff-ncri',
                        'MRFF National Critical Research Infrastructure',
                    ),
                    (
                        'mrff-preventive',
                        'MRFF Preventive and Public Health Research',
                    ),
                    ('mrff-primary-care', 'MRFF Primary Health Care Research'),
                    ('mrff-rart', 'MRFF Rapid Applied Research Translation'),
                    ('mrff-rdi', 'MRFF Research Data Infrastructure'),
                    (
                        'mrff-redi',
                        'MRFF Researcher Exchange and Development Within Industry',
                    ),
                    ('mrff-stem-cell', 'MRFF Stem Cell Therapies Mission'),
                    ('mrff-tbi', 'MRFF Traumatic Brain Injury Mission'),
                    ('mrff-other', 'Other MRFF initiative'),
                    ('rdc-wa', 'Wine Australia'),
                    ('rdc-crdc', 'Cotton RDC'),
                    ('rdc-frdc', 'Fisheries RDC'),
                    ('rdc-grdc', 'Grains RDC'),
                    (
                        'rdc-agrifutures',
                        'Rural Industries RDC (AgriFutures Australia)',
                    ),
                    ('rdc-ael', 'Australian Eggs Ltd'),
                    (
                        'rdc-livecorp',
                        'Australian Livestock Export Corp Ltd (LiveCorp)',
                    ),
                    ('rdc-ampc', 'Australian Meat Processor Corp'),
                    ('rdc-apl', 'Australian Pork Ltd'),
                    ('rdc-awil', 'Australian Wool Innovation Ltd'),
                    ('rdc-dal', 'Dairy Australia Ltd'),
                    ('rdc-fwpa', 'Forest and Wood Products Australia'),
                    ('rdc-hial', 'Horticulture Innovation Australia Ltd'),
                    ('rdc-mla', 'Meat and Livestock Australia'),
                    ('rdc-sral', 'Sugar Research Australia Ltd'),
                    ('act', 'Australian Capital Territory Govt funding'),
                    ('nsw', 'New South Wales Govt funding'),
                    ('nt', 'Northern Territory Govt funding'),
                    ('qld', 'Queensland Govt funding'),
                    ('sa', 'South Australia Govt funding'),
                    ('tas', 'Tasmania Govt funding'),
                    ('vic', 'Victoria Govt funding'),
                    ('wa', 'Western Australia Govt funding'),
                    ('unspecified', 'unspecified'),
                ],
                help_text="Choose an applicable grant subtype from the\n                  dropdown options.  If no option is applicable,\n                  choose 'unspecified' and then fill in the 'Other\n                  funding source details' field below.",
                max_length=128,
                verbose_name='Grant Subtype',
            ),
        ),
        migrations.AlterField(
            model_name='grant',
            name='grant_type',
            field=models.CharField(
                choices=[
                    (None, 'Select a grant type'),
                    ('arc', 'Australian Research Council'),
                    ('nhmrc', 'NHMRC'),
                    ('mrff', 'Medical Research Future Fund (MRFF)'),
                    (
                        'rdc',
                        'Rural Research and Development Corporations (RDCs)',
                    ),
                    (
                        'comp',
                        'Other Australian Federal Govt competitive grant',
                    ),
                    (
                        'govt',
                        'Australian Federal Govt non-competitive funding',
                    ),
                    ('state', 'Australian State / Territory Govt funding'),
                    ('industry', 'Industry funding'),
                    ('ext', 'Other external funding'),
                    ('inst', 'Institutional research funding'),
                    ('nz', 'New Zealand research funding'),
                ],
                help_text='Choose the grant type from the dropdown options.',
                max_length=128,
                verbose_name='Grant Type',
            ),
        ),
    ]
